services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ip_data:/var/www/html
    depends_on:
      - imageportfolio

  imageportfolio:
    image: deinuser/imageportfolio:latest
    volumes:
      - ip_data:/var/www/html
    expose:
      - "9000"

volumes:
  ip_data: