services:
  imageportfolio:
    image: cheinisch/lensfolio:latest
    ports:
      - "8080:80"
    volumes:
      - appdata:/var/www/html
      - userdata_volume:/var/www/html/userdata
    environment:
      - TZ=Europe/Berlin
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_POST_MAX_SIZE=100M

volumes:
  appdata:
  userdata_volume:
