name: Build and Push Nightly Apache Docker Image

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '35 2 * * *'
  workflow_dispatch:  # manuell starten möglich

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image (Apache + PHP)
      run: |
        docker build -f docker/Dockerfile -t cheinisch/lensfolio:nightly .

    - name: Push Docker Image
      run: |
        docker push cheinisch/lensfolio:nightly
