name: ImagePortfolio - Build & Push Docker image

on:
  #push:
    #branches: [main]       # Änderungen im main-Branch
    #tags: ['v*']           # Versionstags wie v1.2.3
  workflow_dispatch:       # manueller Start

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set image tags (VERSION & always latest)
      id: tags
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV
          echo "IS_LATEST=true" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == refs/heads/main ]]; then
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "IS_LATEST=true" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          echo "IS_LATEST=false" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      run: |
        docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.IMAGE_TAG }} .
        if [[ "${{ env.IS_LATEST }}" == "true" && "${{ env.IMAGE_TAG }}" != "latest" ]]; then
          docker tag ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/imageportfolio:latest
        fi

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.IMAGE_TAG }}
        if [[ "${{ env.IS_LATEST }}" == "true" ]]; then
          docker push ${{ secrets.DOCKER_USERNAME }}/imageportfolio:latest
        fi
