name: ImagePortfolio - Build & Push Docker image

on:
  push:
    branches: [main]       # bei Änderungen im main-Branch
    tags: ['v*']           # bei Tags wie v1.2.3
  workflow_dispatch:       # manueller Start im UI möglich

jobs:
  build-on-selfhosted:
    name: Build & Push (Docker, self-hosted Linux)
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract version from tag (or fallback to latest)
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/imageportfolio:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/imageportfolio:latest

  # Beispiel: Tests auf GitHub gehosteten Runnern
  test-on-windows:
    runs-on: windows-latest
    needs: build-on-selfhosted
    steps:
      - run: echo "Windows-Test"
