name: ImagePortfolio - Build & Push Docker image

on:
  push:
    branches: [main]       # bei Änderungen im main-Branch
    tags: ['v*']           # bei Tags wie v1.2.3
  workflow_dispatch:       # manueller Start im UI möglich

jobs:
  build-and-push:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Extract tag
      id: vars
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.VERSION }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/imageportfolio:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/imageportfolio:${{ env.VERSION }}
        docker push ${{ secrets.DOCKER_USERNAME }}/imageportfolio:latest
