name: Build and Push Apache Docker Image

on:
  push:
    tags:
      - 'v*'        # bei neuen Versionstags wie v1.0.0
  workflow_dispatch:  # manuell starten möglich

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version
      id: version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          VERSION="${GITHUB_REF#refs/tags/v}"
        else
          VERSION="latest"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image (Apache + PHP)
      run: |
        docker build -f docker/Dockerfile -t cheinisch/imageportfolio:${{ env.VERSION }} .
        if [[ "${{ env.VERSION }}" != "latest" ]]; then
          docker tag cheinisch/imageportfolio:${{ env.VERSION }} cheinisch/imageportfolio:latest
        fi

    - name: Push Docker Image
      run: |
        docker push cheinisch/imageportfolio:${{ env.VERSION }}
        if [[ "${{ env.VERSION }}" != "latest" ]]; then
          docker push cheinisch/imageportfolio:latest
        fi
